CREATE TABLE IF NOT EXISTS T_TEAM (
    ID                  BIGINT          PRIMARY KEY,
    NAME                VARCHAR(20)     NOT NULL,
    PRODUCT             VARCHAR(20)     NOT NULL,
    DEFAULT_LOCATION    VARCHAR(10)     NOT NULL,
    CREATED_AT          TIMESTAMP       NOT NULL,
    MODIFIED_AT         TIMESTAMP       NOT NULL
);
CREATE SEQUENCE IF NOT EXISTS SEQ_TEAM_ID;

CREATE TABLE IF NOT EXISTS T_RACK (
    ID                  BIGINT          PRIMARY KEY,
    SERIAL_NUMBER       TEXT            NOT NULL,
    TEAM_ID             BIGINT          NOT NULL,
    STATUS              VARCHAR(20)     NOT NULL,
    DEFAULT_LOCATION    VARCHAR(10)     NOT NULL,
    CREATED_AT          TIMESTAMP       NOT NULL,
    MODIFIED_AT         TIMESTAMP       NOT NULL,
    CONSTRAINT FK_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES T_TEAM(ID)
);
CREATE SEQUENCE IF NOT EXISTS SEQ_RACK_ID;

CREATE TABLE IF NOT EXISTS T_RACK_ASSET (
    ID          BIGINT          PRIMARY KEY,
    RACK_ID     BIGINT          NOT NULL,
    ASSET_TAG   VARCHAR(10)     NOT NULL,
    CONSTRAINT FK_RACK_ID FOREIGN KEY (RACK_ID) REFERENCES T_RACK(ID)

);
CREATE SEQUENCE IF NOT EXISTS SEQ_RACK_ASSET_ID;

CREATE TABLE IF NOT EXISTS T_TEAM_MEMBER (
    ID              BIGINT          PRIMARY KEY,
    TEAM_ID         BIGINT          NOT NULL,
    CTW_ID          VARCHAR(10)     NOT NULL,
    NAME            VARCHAR(20)     NOT NULL,
    CREATED_AT      TIMESTAMP       NOT NULL,
    MODIFIED_AT     TIMESTAMP       NOT NULL,
    CONSTRAINT FK_TEAM_ID FOREIGN KEY (TEAM_ID) REFERENCES T_TEAM(ID)
);
CREATE SEQUENCE IF NOT EXISTS SEQ_TEAM_MEMBER_ID;

CREATE TABLE IF NOT EXISTS T_BOOKING (
    ID              BIGINT      PRIMARY KEY,
    RACK_ID         BIGINT      NOT NULL,
    REQUESTER_ID    BIGINT      NOT NULL,
    BOOK_FROM       TIMESTAMP   NOT NULL,
    BOOK_TO         TIMESTAMP   NOT NULL,
    CREATED_AT      TIMESTAMP   NOT NULL,
    MODIFIED_AT     TIMESTAMP   NOT NULL,
    CONSTRAINT FK_RACK_ID FOREIGN KEY (RACK_ID) REFERENCES T_RACK(ID),
    CONSTRAINT FK_REQUESTER_ID FOREIGN KEY (REQUESTER_ID) REFERENCES T_TEAM_MEMBER(ID)
);
CREATE SEQUENCE IF NOT EXISTS SEQ_BOOKING_ID;
