DROP SEQUENCE IF EXISTS SEQ_BOOKING_ID;
DROP SEQUENCE IF EXISTS SEQ_RACK_ASSET_ID;
DROP SEQUENCE IF EXISTS SEQ_RACK_ID;
DROP SEQUENCE IF EXISTS SEQ_TEAM_MEMBER_ID;
DROP SEQUENCE IF EXISTS SEQ_TEAM_ID;