name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        uses: RAlvesCTW/academy/.github/actions/maven_build@main
      - name: Build Docker Image
        uses: RAlvesCTW/academy/.github/actions/docker_build@main
        with:
          dockerfile_path: src/main/docker/Dockerfile.jvm
      - name: List Docker Image
        run: docker images

      - name: Docker Hub
        uses: RAlvesCTW/academy/.github/actions/docker_login@main
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}